apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-despacho
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-despacho
  template:
    metadata:
      labels:
        app: back-despacho
    spec:
      containers:
      - name: back-despacho
        image: 306299936055.dkr.ecr.us-east-1.amazonaws.com/innovatech-db:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081 # <--- CAMBIADO A 8081 (Como pide tu Spring Boot)
        env:
        - name: DB_ENDPOINT
          value: "mysql-service"
        - name: DB_PORT
          value: "3306"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "innovatech2026"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/innovatech?allowPublicKeyRetrieval=true&useSSL=false"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: back-despacho-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 8081       # <--- CAMBIADO A 8081
    targetPort: 8081 # <--- CAMBIADO A 8081
  selector:
    app: back-despacho
