server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Redirigir peticiones de ventas con los slashes '/' de limpieza corregidos
    location /ventas/ {
        proxy_pass http://back-ventas-service:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Redirigir peticiones de despachos con los slashes '/' de limpieza corregidos
    location /despachos/ {
        proxy_pass http://back-despacho-service:8081/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
